### ISSUE TITLE
Get Started docs - Add a component to an existing page throws error

### ISSUE THREAD

**Issue by bjephson** [blackbaud/skyux2-docs#1011]
Following the steps in Get Started / Basics / Edit a SPA, in the section titled [**Add a component to an existing page**](https://developer.blackbaud.com/skyux/learn/get-started/basics/edit-project#add-a-component-to-an-existing-page) will lead to a runtime error. 

Up to this point, the instructions haven't mentioned updating `app-sky.module.ts` to include the `SkyCardModule`. This means the elements of `sky-card` are not known when you add it to a page.

Need to add a step to the instructions about including the `SkyCardModule` to https://github.com/blackbaud/skyux2-docs/blob/master/src/app/learn/get-started/basics/edit-project/index.html.

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and fixed in https://github.com/blackbaud/skyux2-docs/pull/1032
