### ISSUE TITLE
Add Accessibility testing docs to site

### ISSUE THREAD

**Issue by Blackbaud-DeniseCisneros** [blackbaud/skyux2-docs#1013]
Add Accessibility testing docs from [`skyux-lib-testing`](https://github.com/blackbaud/skyux-lib-testing#accessibility-testing) to `@skyux-sdk/testing`.

Might also be a good idea to add this content to the [Test for accessibility](https://developer.blackbaud.com/skyux/learn/accessibility/test) section of SKY UX docs site.

**Comment by Blackbaud-SteveBrush** [comment]
We actually have the docs written up on the docs site, but we need to link to the [Accessibility tests](https://developer.blackbaud.com/skyux/learn/get-started/advanced/accessibility-unit-tests) page under the `a11y` property in `skyuxconfig.json`, found here: https://developer.blackbaud.com/skyux/learn/reference/configuration#a11y.

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed and merged in https://github.com/blackbaud/skyux2-docs/pull/1022
