### ISSUE TITLE
Updated themed components section and remove box component section from modern docs

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux2-docs#1015]
The "Themed components" section and "Box component" section on the modern theme configuration page is outdated. The "Themed components" section should be updated with verbiage and a link pointing readers to the components page, and the "Box component" section should be removed altogether as it is now documented in the components docs.

https://developer.blackbaud.com/skyux-modern/learn/configure-modern-theme

**Comment by blackbaud-johnly** [comment]
Addressed in https://blackbaud.visualstudio.com/Products/_git/skyux-spa-skyux-modern/pullrequest/132811.
