### ISSUE TITLE
"Update SKY UX modules" docs are outdated

### ISSUE THREAD

**Issue by Blackbaud-PaulCrowder** [blackbaud/skyux2-docs#1018]
The alert about installing `@skyux-sdk/builder-plugin-migrate` should be removed since the `skyux upgrade` command has been moved to SKY UX CLI. We might also want to tweak the verbiage "This command pulls in the latest version" to be more specific, since it doesn't pull in the latest major version. Maybe "This command pulls in the latest minor or patch version".

https://developer.blackbaud.com/skyux/learn/get-started/basics/modules#update-sky-ux-modules

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/1020.
