### ISSUE TITLE
Add tips for developers for NPM CLI

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#1030]
During our UI Guild meeting we talked about improving the Getting Started guide to instruct users to:
- Run `skyux upgrade` frequently and monitor the output (especially peer dependency warnings).
- Run `npm audit` frequently to check for any security vulnerabilities.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/1031.
