### ISSUE TITLE
Module Lazy Loading ?

### ISSUE THREAD

**Issue by doctorRush** [blackbaud/skyux2-docs#1071]
Hello Team,

How the Concept of Module Lazy Loading . As by default SKY UX doesn't provide the facility to generate module from cli.
Please Respond ASAP.

Regards
Naman Gupta

**Comment by Blackbaud-KerryCampbell** [comment]
Lazy loading is not supported in SKY UX 4 but it will be available in the future SKY UX 5 version which will utilize Angular CLI.
