### ISSUE TITLE
Document / demo Inline Form component

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#246]
*This should be added to the `skyux2-docs` repo, as it is a new component.*

See https://github.com/blackbaud/skyux-inline-form/issues/3

The inline form component allows a form to be displayed in context, without having to open a modal. Most commonly it will be used within a repeater or grid row or tile section. The inline form component provides the design, transition animations, and buttons. Actual contents of the form and handling of button actions is up to the implementer.

# Properties
`config` - Optional. Allows consumer to configure inline-form with different buttons (done/save/close/cancel/etc...). This property accepts values of type `SkyInlineFormConfig`. Default will display a `Done` and `Cancel` button.

`showForm` - Controls when the inline-form is shown. Setting this to `true` will hide the current content and display the form. Type: Boolean.

`template` - The template for the form. Supplied value is a `TemplateRef` link to consumer-defined template.

# Events
`close` — An event that the inline form component emits when a button is clicked. It emits a `SkyInlineFormCloseArgs` object with a `reason` property that indicates whether the inline form was saved or closed without saving. Possible `reason` values are as follows: `save`, `delete`, `cancel`. 

# `SkyInlineFormConfig` properties
`buttonLayout` - Allows consumer to configure inline-form with different button layouts. This property accepts a `SkyInlineFormButtonLayout` enum. Acceptable values are `Custom`, `DoneCancel`, `DoneDeleteCancel`, `SaveCancel`, and `SaveDeleteCancel`. If a `Custom` value is provided, the consumer must also define the following `buttons` property.

`buttons` - Optional. Allows consumer to create their own custom buttons on the inline-form. This property accepts an array of `SkyInlineFormButtonConfig` properties.

# `SkyInlineFormButtonConfig` properties
`action` - Specifies an identifier to return when users select the button. Type: string.

`text` - Specifies the label for the button. Type: string.

`styleType` - Optional. Specifies a [SKY UX button class](https://developer.blackbaud.com/skyux/components/button#classes) to apply to the button. The valid options are `primary` to format the primary action on the dialog, `default` to format a secondary action, and `link` to format an action that takes users to another page. Default: `default` Type: string.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/231.
