### ISSUE TITLE
list-view-grid > Document new properties for multiselect

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#250]
### Properties

`enableMultiselect` — (Optional.) Indicates whether to enable the multiselect feature to display a column of checkboxes on the left side of the grid. You can specify a unique ID with the `multiselectRowId` property; if not, then multiselect defaults to the `id` property on the data object. Enabling this property will also display the multiselect toolbar, which features  "Select all", "Clear all" and "Show only selected" controls. This property accepts `boolean` values. _(Default: false)_

`multiselectRowId` — (Optional.) Specifies a unique ID that matches a property on the list's `data` object. By default, the property defaults to the `id` property on the list's `data` object. This property accepts `string` values.

### Events

`multiselectSelectionChange` — Fires when the selection of multiselect checkboxes changes. Emits an array of IDs for the selected rows based on the `multiselectRowId` property that the consumer provides.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/223.
