### ISSUE TITLE
Document how to bump version for internal-only libraries on VSTS

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#252]
It's not clear from our documentation how to bump major, minor, and patch versions for VSTS library builds.

**Comment by Blackbaud-BobbyEarl** [comment]
Closing this for a few reasons:
- This process now relies simply on the version in `package.json` at the time of running `git tag` (or using the UI).
- If we still want to document that process, this task would be better represented in Azure Boards.
