### ISSUE TITLE
Document (and demonstrate) the best practice method for including a custom stylesheet in your SPA

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#255]
This, in app-extras, or?

```
require('style-loader!./styles.scss');
```

Whatever we decide, we should put this in the template, too.

**Comment by Blackbaud-DeniseCisneros** [comment]
Documented under `styles`
https://developer.blackbaud.com/skyux/learn/reference/configuration#app

**Comment by blackbaud-johnly** [comment]
Thanks for catching that!
