### ISSUE TITLE
Review components documentation

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#256]
I've reviewed components documentation in fits and starts, but they need a thorough review for style/grammar/wording/etc. and also clarity/content/accuracy to find any holes for developers. (I've received feedback that the documentation is lacking for some components. From Kris Mahon: "Some of the components seem fairly well documented, but others like “Tiles” seems very lacking (I honestly have no idea how to use the tiles properly from that page – the code shows a directive that isn’t even talked about, and doesn’t show examples of the any of the directives that are mentioned.") 

- [x] Action button
- [x] Alert
- [x] Autocomplete
- [x] Avatar (Intermediate)
- [x] Buttons
- [x] Card (Intermediate)
- [x] Checkbox
- [x] Code block
- [x] Colorpicker
- [x] Confirm
- [x] Copy to clipboard
- [x] Date range picker
- [x] Datepicker
- [x] Definition list
- [x] Dropdown
- [x] Email validation
- [ ] Error
- [ ] File attachments
- [x] Filter
- [ ] Fluid grid
- [ ] Flyout
- [x] Form
- [ ] Grid
- [ ] Help inline
- [ ] Highlight
- [ ] Icon
- [x] Infinite scroll
- [ ] Key info
- [ ] Label
- [ ] Link records
- [ ] List
- [ ] List filters
- [ ] List paging
- [ ] List toolbar
- [x] List view checklist
- [x] List view grid
- [x] Lookup
- [ ] Media queries
- [x] Modal
- [ ] Navbar (Advanced)
- [ ] Numeric (Basic)
- [ ] Page summary
- [x] Paging
- [x] Phone field
- [x] Popover
- [x] Progress indicator
- [x] Radio button
- [x] Repeater
- [x] Search
- [x] Sectioned form
- [x] Select field
- [ ] Sort
- [x] Status indicator
- [x] Summary action bar
- [x] Tabs
- [x] Text expand
- [x] Text expand repeater
- [x] Tile
- [x] Timepicker
- [x] Toast
- [ ] Tokens
- [ ] Toolbar (address https://github.com/blackbaud/skyux2/issues/1457 when I review the toolbar component)
- [x] URL validation
- [x] Vertical tabs
- [ ] Wait
- [ ] Wizard

  
***Related:***
- [ ] https://github.com/blackbaud/skyux2/issues/1457
- [ ] https://github.com/blackbaud/skyux2/issues/1455

**Comment by Blackbaud-MichaelCollier** [comment]
Will clean these up and address as docs are converted.
