### ISSUE TITLE
Document `SkyLibResources` provider and pipe

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#259]
Source: https://github.com/blackbaud/skyux-i18n/blob/master/src/app/public/modules/i18n/lib-resources.service.ts

**Comment by Blackbaud-SteveBrush** [comment]
### Install the plugin

**Install the SKY UX Builder plugin:**

```
npm install --save-dev --save-exact @skyux-sdk/builder-plugin-skyux
```

**List the plugin in your `skyuxconfig.json` file:**

```
{
  "plugins": [
    "@skyux-sdk/builder-plugin-skyux"
  ]
}
```

### Create a resources provider

Create a new directory named `plugin-resources` at `./src/app/public/plugin-resources` (the name and location of this directory is important!).

Inside the `plugin-resources` directory create a new file named  `my-library-resources-provider.ts` (replace `my-library` with the name of your library).

<img width="521" alt="Screen Shot 2019-04-11 at 10 13 47 AM" src="https://user-images.githubusercontent.com/12497062/55964320-84f8b700-5c42-11e9-8379-a59df1bec8f4.png">

The contents of the `my-library-resources-provider.ts` file should look like this (replace `MyLibrary` with the name of your library):

```
import {
  SkyAppLocaleInfo,
  SkyLibResourcesProvider
} from '@skyux/i18n';

export class MyLibraryResourcesProvider implements SkyLibResourcesProvider {
  public getString: (localeInfo: SkyAppLocaleInfo, name: string) => string;
}

```

### Create a resources module

The resources module will be shared by all modules in your library that need access to locale resources strings.

In a directory that's used for shared types, create a new Angular module with the following contents (replace `MyLibrary` with the name of your library):

<img width="465" alt="Screen Shot 2019-04-11 at 10 17 01 AM" src="https://user-images.githubusercontent.com/12497062/55964626-0b14fd80-5c43-11e9-9f2a-071da050a09a.png">

```
import {
  NgModule
} from '@angular/core';

import {
  SkyI18nModule,
  SKY_LIB_RESOURCES_PROVIDERS
} from '@skyux/i18n';

import {
  MyLibraryResourcesProvider
} from '../../plugin-resources/my-library-resources-provider';

@NgModule({
  providers: [{
    provide: SKY_LIB_RESOURCES_PROVIDERS,
    useClass: MyLibraryResourcesProvider,
    multi: true
  }],
  exports: [
    SkyI18nModule
  ]
})
export class MyLibraryResourcesModule { }
```

### Additional setup

Now you may import the new `MyLibraryResourcesModule` into any of your modules that require access to locale resource strings. This will allow the module to use the `skyLibResources` pipe, and the `SkyLibResourcesService`.

**some-other.module.ts**

```
import {
  MyLibraryResourcesModule
} from './shared/my-library-resources.module';

@NgModule({
  // ...

  imports: [
    SkyLibraryResourcesModule
  ]

  // ...
})
export class MyLibrarySomeOtherModule { }

```

**Comment by Blackbaud-DeniseCisneros** [comment]
Merged in https://github.com/blackbaud/skyux2-docs/pull/408
