### ISSUE TITLE
Document phone field component

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#260]
See https://github.com/blackbaud/skyux2/issues/158.

**Comment by Blackbaud-BobbyEarl** [comment]
https://github.com/blackbaud/skyux2-docs/pull/436

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/436 and https://github.com/blackbaud/skyux2-docs/pull/521.
