### ISSUE TITLE
Document the Date range picker component

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux2-docs#261]
For the Pr resolving #1105

**Comment by Blackbaud-SteveBrush** [comment]
A "calculator" is an object that returns two `Date` objects to represent a date range.

The calculator can be configured to have a `validate` function, which validates the two dates selected by the user (from the date pickers). This is useful if you need to check if the two selected dates are compatible (for example, if the start date is after the end date).

The calculator _must_ be configured to have a `getValue` function--which gets called after the calculator's `validate` function--and returns a range of two `Date` objects (this is especially useful if the calculation involves a relative date, such as "the next fiscal year").

The calculator's `type` can also be set to one of:
- `SkyDateRangeCalculatorType.After`, which shows the start date picker.
- `SkyDateRangeCalculatorType.Before`, which shows the end date picker.
- `SkyDateRangeCalculatorType.Range`, which shows both the start date and the end date pickers.
- `SkyDateRangeCalculatorType.Relateve`, which shows neither of the pickers.

**Create a new calculator with the `SkyDateRangeService`:**

```
const calculator = this.dateRangeService.createCalculator({
  shortDescription: 'My calculator',
  type: SkyDateRangeCalculatorType.Relative,
  getValue: () => {
    return {
      startDate: new Date(),
      endDate: new Date()
    };
  },
  validate: (startDateInput, endDateInput) => {
    if (isInvalid) {
      return {
        'myError': true
      };
    }
  }
});
```

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/432.
