### ISSUE TITLE
Document copy to clipboard component for SKY UX

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#262]
Create SKY UX docs for Stache component: https://developer.blackbaud.com/stache/content/clipboard.

**Comment by Blackbaud-DeniseCisneros** [comment]
PR for docs https://github.com/blackbaud/skyux2-docs/pull/313

**Comment by Blackbaud-DeniseCisneros** [comment]
PR's been merged
