### ISSUE TITLE
Document `SkyAuthHttpClient` alongside docs for `SkyAuthHttp`

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#263]
Issue for dev work: https://github.com/blackbaud/skyux2/issues/1240.

Related Slack conversation: https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1547674998204900.

**Comment by Blackbaud-SteveBrush** [comment]
Closing in favor of https://github.com/blackbaud/skyux2-docs/issues/257
