### ISSUE TITLE
Document SkyAppWindowRef

### ISSUE THREAD

**Issue by blackbaud-conorwright** [blackbaud/skyux2-docs#266]
The `SkyAppWindowRef` is a utility we provide and recommend use of. Once injected into a component, it can be used to reference the `window` without using the global variable directly and this is the recommended way to interact with things on the window like localStorage or viewport events.

You can use it to get the window by calling the `getWindow` method: `SkyAppWindowRef.getWindow()`
Right now it is located in `@blackbaud/skyux-builder/runtime`, but will soon be moved to `@skyux/core`

**Comment by Blackbaud-MatthewMiles** [comment]
Took a swing at this.  Let me know if you have any feedback!

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/703.
