### ISSUE TITLE
Isolate the `SkySelectField` interface into a separate section on the docs

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#269]
The interface for `SkySelectField` is documented, but it might be better to create a separate section to describe its properties in more detail.

"data — Defines a data source to populate the select field component's modal with items that users can select. **The SkySelectField type extends the any type and supports id, label, and category values for the data objects that you inject into the select field component.**"
https://developer.blackbaud.com/skyux/components/select-field

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/368.
