### ISSUE TITLE
Document SkyFormat

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#272]
Missing documentation for this was pointed out on Slack: https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1536863373000100

Also check https://github.com/blackbaud/skyux-core/issues/5.

**Comment by Blackbaud-DeniseCisneros** [comment]
Chatted with @Blackbaud-PaulCrowder about this. He said `SkyFormat` is an internal implementation of SKY UX not meant for SPA consumption but may be revisited in the future.

Marking as closed for now.
