### ISSUE TITLE
Document how to manage connection strings

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#278]
A question came up on Slack about how to set up environment-specific API URLs: https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1517377595000097. We have internal docs on engineering system (https://docs.blackbaud.com/engineering-system-docs/learn/spa/spa-connection-strings), and @Blackbaud-IsaacAggrey recommended including something on the external site as well. I'm creating this issue to follow up on this suggestion.

**Comment by Blackbaud-BobbyEarl** [comment]
In addition to the internal link posted, I think https://developer.blackbaud.com/skyux/learn/reference/configuration/additional-config-files accurately documents the available functionality (which was introduced via https://github.com/blackbaud/skyux2-docs/pull/49).

**Comment by Blackbaud-IsaacAggrey** [comment]
@Blackbaud-BobbyEarl The functionality is indeed documented, but the idea here was a slight documentation improvement if you take a look at the Slack thread mentioned - the doc here could use the example for folks to make the connection.

I don't mind making the contribution if it would be accepted.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-IsaacAggrey if you want to create a PR into the docs repo, that would be great. But feel free to reach out to me directly so that we can discuss the changes you are looking for and I can update the docs. Whichever works best for you. Thanks!
