### ISSUE TITLE
Document guidelines for new page behavior

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#279]
Based on @Blackbaud-MattGregg's docs on navigation guidelines, create new topic in the Design section with guidance on the behavior of the back button. Paul said the behavior described in Matt's docs should be the default and that we just need documentation to call out that this is supposed to be the behavior unless something changes. Here's the notes form Matt's docs at https://blackbaudinc.app.box.com/s/9jmk38pmy2nb0zgrcoujyirwz55wcs17:

New page behaviors 
This section covers what interactions within SKY experiences should create a new URL and entry in the browser’s history to enable users to utilize the browser’s back button. 

Back button
Actions such as navigating to a completely new context (i.e., new record, list, section, etc.) should insert a new entry in the browser history with a new page title and enable a user to select the browser’s back button to go back to the previous page/view.

Sometimes this can be a judgement call. Use this rule of thumb:
If the majority of the page content changes or a user would perceive a significant change of context, create a new page in browser history.  

Inline interactions should not create a new URL or an entry in the browser’s history (e.g., steps in a wizard, opening detail panel, filtering/sorting)

**Comment by Blackbaud-MattGregg** [comment]
Just a note this isn't accessibility-related. It's just how people expect the web sites and browser history/back buttons to function.

**Comment by blackbaud-johnly** [comment]
Closing as outdated as we migrate docs tasks over to ADO. This was never a high priority, and when Denise looked into it, she ran into several issues determining what/how to document. Rather than starting over from scratch with something this old, I'm closing. We can always reopen if it turns out we really need some docs on this.
