### ISSUE TITLE
Document how to run unit tests in different browsers

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#286]
Update CONTRIBUTING.md and https://developer.blackbaud.com/skyux2/learn/get-started/2.-initial-setup to call out that you need to have the appropriate karma-<browsername>-launcher installed in the package.json. We only have chrome and firefox there currently. 

And then in the CONTRIBUTING.md file's "Write unit tests" section and https://developer.blackbaud.com/skyux2/learn/reference/tests, explain that to run unit tests in different browsers, you add the browsers to the `browsers` property in the  `local.karma.conf.js` file. We don't currently have anything about this in the docs.

Also, the official recommendation is not to add a browser but to change it. Otherwise you run tests in both browsers and it's be harder to pinpoint whatever error you're getting.

**Comment by Blackbaud-BobbyEarl** [comment]
Documented at https://app.blackbaud.com/browserstack/
