### ISSUE TITLE
Document how to write and implement Builder plugins

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#287]
We need to document how to write and implement `skyux-builder-plugin-` plugins.

**Here's an example plugin:**
https://github.com/blackbaud/skyux-builder-plugin-stache

This pull request is related: https://github.com/blackbaud/skyux-builder/pull/156

**package.json**
```
{
  "dependencies": {
    "@blackbaud/skyux-builder-plugin-stache": "^1.0.0"
  }
}
```

**skyuxconfig.json**
```
{
  "plugins": [
    "@blackbaud/skyux-builder-plugin-stache"
  ]
}
```

**Plugin's index.js file:**
The simplest form of a plugin would have an index.js file that includes:
```
module.exports = {
  // content = a string representation of the file's contents
  // resourcePath = the absolute path to the file
  // skyPagesConfig = the prepared config that includes skyuxconfig.json and builder's defaults
  preload(content, resourcePath, skyPagesConfig) {
    return content;
  };
}
```

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/456.
