### ISSUE TITLE
Document building and hosting outside of the SKY UX Host system

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#289]
David Owens reached out to Matt Bodily for feedback on the SKY UX 2 docs based on his OTG team's experience. He said info about building and hosting outside of the SKY UX Host system was the only thing that he wasn't able to find in the docs.

**Comment by Blackbaud-BobbyEarl** [comment]
Closing in favor of https://github.com/blackbaud/skyux2-docs/issues/409
