### ISSUE TITLE
Update guidance on using unit tests for pact testing

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#293]
@Blackbaud-KrisMahon is converting bulk import's e2e pact tests to unit tests and is finding this difficult with the existing docs. He suggested several changes:
•	A full code sample to use as an example would be particularly helpful. 
•	The "Override the provider URL" section in the existing documentation is confusing.
•	The description of the host/port settings is confusing. If you need to override the URL elsewhere, how do you know what it is if you rely on the defaults? (Or something like that. I’m taking these notes after the fact and might have this point off a little.)
•	What file are users supposed to apply config settings? The main file, or a separate pact config file? The latter seems to make more sense, but we don’t say that because it didn't come up when the original documentation was created.
•	Some pact configuration options are missing. Kris said the ones we have are verbatim from another file that includes additional options that we should be able to use here. Need to look into that.

I mentioned this issue to @blackbaud-danbowman, and he suggested we might want to add a tutorial to Buzzbaud. ... Hopefully Kris will add notes to the issue if I got anything wrong or missed anything from our conversation.

**Comment by Blackbaud-AlexKingman** [comment]
As pointed out in blackbaud/skyux-sdk-builder#43, there is some disparity between [our `pact` properties in the `skyux-config.json` file](https://developer.blackbaud.com/skyux/learn/reference/configuration#pacts), and their corresponding properties in the [mock provider service (pact-js)](https://github.com/pact-foundation/pact-js/blob/master/src/dsl/options.ts)

@Blackbaud-KrisMahon further points out above:
> Under the hood, we just use the official pact-js config options.

Pact-js owns these properties and they're documented in the [pact-js consumer API docs](https://github.com/pact-foundation/pact-js#api). With these things in mind, we should probably no longer replicate documentation of these properties. However, we do set some defaults in [skyux-sdk-builder-plugin-pact](https://github.com/blackbaud/skyux-sdk-builder-plugin-pact/blob/master/lib/config/karma/pact.karma.conf.js#L32):
- `log` defaults to '/logs/pact-[provider].log`
- `dir` defaults to `/pacts`
- `pactFileWriteMode` defaults to `overwrite`

Is there a way we can still provide guidance for using these properties while pointing towards the pact-js docs to find the official documentation?
