### ISSUE TITLE
Address docs feedback on experience for third-party developers

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#300]
@Blackbaud-BenLambert is going through the SKY UX docs to evaluate the experience from a third-party developer's perspective and passing along feedback as he goes. Creating this issue to follow up on his feedback and update the docs.

**Comment by Blackbaud-BobbyEarl** [comment]
This has been resolved in numerous PRs since initial creation.  The last of which will be https://github.com/blackbaud/skyux2-docs/issues/409
