### ISSUE TITLE
Update docs for static assets to describe how to add static assets through .ts file

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#301]
Upate https://developer.blackbaud.com/skyux/learn/get-started/advanced/include-static-assets to include a section describing how to reference static assets in component.ts files. This came up in a Slack thread: https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1534276123000100.

**Comment by Blackbaud-BobbyEarl** [comment]
Duplicate of #302.  Also fixed via https://github.com/blackbaud/skyux2-docs/pull/65
