### ISSUE TITLE
Update static assets docs with recommendation about how to reference an asset file in TS code

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#302]
Update docs at https://developer.blackbaud.com/skyux/learn/get-started/advanced/include-static-assets to reflect the recommendation in https://github.com/blackbaud/skyux2/issues/1863.

**Comment by Blackbaud-BobbyEarl** [comment]
Fixed via https://github.com/blackbaud/skyux2-docs/pull/65
