### ISSUE TITLE
Update docs to address feedback on library names

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#308]
Feedback on library names:

1 - https://developer.blackbaud.com/skyux/learn/reference/configuration doesn't talk about libraries - should it?
2 - also on that page, it mentions a `blackbaud-skyux-spa` prefix - is that correct?
3 - the library template includes a `myLibrary` setting in the `appSettings`, which also has a name - maybe mention that on this page https://developer.blackbaud.com/skyux/learn/reference/component-libraries?

**Comment by Blackbaud-AlexKingman** [comment]
Closed as addressed.
