### ISSUE TITLE
Update references across the site for SKY UX 3

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux2-docs#320]
Across the entire docs site, we reference quite a few things by it's old SKY UX 2 location.

We should go through the site with a fine-tooth comb to find these and update them.  That should be pretty quick and painless.

The biggest outstanding question will be do we simply update the reference, do we leave the old + add the new locations, or do we tag the old docs site and make this change on the new version.

Example:  https://developer.blackbaud.com/skyux/design/styles/color

**Comment by Blackbaud-DeniseCisneros** [comment]
In addition to the one Bobby pointed out, `skyux-builder` is referenced in the following files:

- https://developer.blackbaud.com/skyux/learn/get-started/advanced/accessibility-analyzer
- https://developer.blackbaud.com/skyux/learn/get-started/advanced/accessibility-unit-tests
- https://developer.blackbaud.com/skyux/learn/get-started/advanced/include-static-assets
- https://developer.blackbaud.com/skyux/learn/get-started/advanced/localization
- https://developer.blackbaud.com/skyux/learn/get-started/basics/update-components
- https://developer.blackbaud.com/skyux/learn/reference/component-libraries
- https://developer.blackbaud.com/skyux/learn/reference/configuration/additional-config-files
- https://developer.blackbaud.com/skyux/learn/reference/configuration/apply-appsettings
- https://developer.blackbaud.com/skyux/learn/reference/configuration
- https://developer.blackbaud.com/skyux/learn/reference/faq

Are we only concerned with references that are user-facing in docs or in typescript and json files too? If it's the latter, this list grows a bit.

**Comment by Blackbaud-BobbyEarl** [comment]
Very shortly (should be released today), we'll also need to account for `@blackbaud/skyux-cli` changing to `@skyux-sdk/cli`.

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and merged in https://github.com/blackbaud/skyux2-docs/pull/355
