### ISSUE TITLE
Research using compodoc to automate documentation for components

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#343]
See: https://github.com/compodoc/compodoc

**Comment by Blackbaud-SteveBrush** [comment]
Compodoc is opinionated in which comment tags (e.g., `@param`, etc.) it supports, since it's an Angular-focused utility. TypeDoc pulls in all tags in the comment, regardless, which allows us to have more flexibility.

TypeDoc supports markdown in the comment out of the box.

Compodoc currently doesn't support descriptions for each value in an enumerator, whereas TypeDoc does. This was the biggest disparity that forced me to consider other options. For example, the following comments are only supported by TypeDoc (Compodoc supports the top-most comment, but not the comments for each of the values):

```
/**
 * The description for the enum.
 */
export enum Foo {
  /**
   * The description for Foo.Bar.
   */
  Bar = 0
}
```

**Comment by Blackbaud-SteveBrush** [comment]
TypeDoc also includes a Node.js API; which is useful for automation.

**Comment by Blackbaud-AlexKingman** [comment]
Research complete. :approved:
