### ISSUE TITLE
Docs: Use consistent verbiage when referring to forms

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#352]
https://developer.blackbaud.com/skyux/components/select-field#demo
https://developer.blackbaud.com/skyux/components/datepicker#demo
https://developer.blackbaud.com/skyux/components/timepicker#demo

there are two types of way to do forms: reactive and template-driven.

my understanding is that BB devs are encouraged to use reactive forms. that may not have been officially declared like i did for the BB teams in austin but i think skyux devs concur.

but, from a docs standpoint, one of the above docs uses “standard” to refer to template-driven. i don't think template-driven is BB's standard. it also puts T-D first over reactive in the doc, kind of conveying that T-D is in fact the standard. 

should we even be putting template-driven in the docs if we dont suggest devs use it? one of those above docs takes the tact of not including template-driven at all.

maybe we should include T-D tho b/c these are open docs and non-:bb: devs use T-D?

whatever the answers are to the above questions, there might be some inconsistencies in the form-related component docs that are conveying something that might not be intended.

### Impact

it's more of an impact for _new_ devs that don't really know what you're talking about when it comes to reactive vs T-D

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-demos/pull/26 and https://github.com/blackbaud/skyux2-docs/pull/688. Other components have already been cleaned up as we refined those demos.
