### ISSUE TITLE
Update docs for Node.js prerequisite

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#369]
The https://developer.blackbaud.com/skyux/learn/get-started/prereqs/initial-setup#nodejs documentation should either tell users to install with the global flag, or it should be moved to make it clear that this step is part of setting up a spa, not as a machine prerequisite.

Also, the section explains that we "require at least version 6" of Node.js, but the install command for `windows-build-tools` fails for any version less than 8. The current verbiage is designed to let users know that at we don't have a strict version requirement, but it either needs to be updated to reflect the minimum version that is actually usable or to include a caveat explaining that other tools might require later versions. We may also want to say that v10 is the recommended version but I need to confirm this with @Blackbaud-BobbyEarl.

This issue was based on internal feedback at the Blackbaud-only Slack thread at https://blackbaud.slack.com/conversation/C4FJT1171/p1553612282123200.

**Comment by Blackbaud-BobbyEarl** [comment]
I'm fine with tightening our verbiage to say we suggest LTS Dubnium.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/382.
