### ISSUE TITLE
Provide more guidance on placeholder text

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#379]
Update design guidelines at https://developer.blackbaud.com/skyux/design/guidelines/form-design#field-usability to flesh out guidance around placeholder text and provide examples.

**Comment by Blackbaud-SteveBrush** [comment]
This is related to the input field masking work effort; on-hold until we get that stuff ironed out.

**Comment by blackbaud-johnly** [comment]
You can use a small amount of placeholder text if users need a hint with data entry.
Do not use placeholder text in place of field labels.
Placeholder text is often more useful as persistent inline help text if it’s needed at all.  The main use case would be inputs that don’t have a label, such as “Find in list” for searching lists.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/893.
