### ISSUE TITLE
Split TextExpand and TextExpandRepeater into separate docs

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux2-docs#389]
They can be cross referenced to avoid any confusion.

The driving force for this is simplifying the template and verbiage for module location/installation.

**Comment by blackbaud-johnly** [comment]
Thanks, @Blackbaud-BobbyEarl. I mentioned text expand in https://github.com/blackbaud/skyux2-docs/issues/384 and thought it might require its own docs issue, but I hadn't gotten to that issue yet. We'll try to handle both of these as quickly as possible.

**Comment by Blackbaud-BobbyEarl** [comment]
Ah good catch on the correlation @blackbaud-johnly.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/398.
