### ISSUE TITLE
typo in SkyAuthHttpClientModule docs 

### ISSUE THREAD

**Issue by Blackbaud-TimMcVicker** [blackbaud/skyux2-docs#391]
On https://developer.blackbaud.com/skyux/learn/reference/helpers/SkyAuthHttpClientModule#use-skyauthhttpclientmodule-to-communicate-with-backend-services

the module is called SkyAuthHttpClientModule in some places but SkyAuthClientHttpModule in other places (note the HttpClient vs the ClientHttp)

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/393.
