### ISSUE TITLE
Document `--headless` flag for CLI test commands

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#397]
```
skyux test --headless
skyux watch --headless
skyux e2e --headless
```

Adding this flag will run unit and e2e tests in Chrome's "headless" mode, which essentially means the browser instance is executed in the background, without opening a visible browser.

Related pull request: https://github.com/blackbaud/skyux-sdk-builder/pull/78

More information about headless Chrome: https://developers.google.com/web/updates/2017/04/headless-chrome

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/410.
