### ISSUE TITLE
List Filters > package is wrong

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#415]
https://developer.blackbaud.com/skyux/components/list/filters

Defined in `SkyListFiltersModule` in NPM package `@skyux/lists`

... should be ...

Defined in `SkyListFiltersModule` in NPM package `@skyux/list-builder`

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed in https://github.com/blackbaud/skyux2-docs/pull/416
