### ISSUE TITLE
Grids > update `sortField` property

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#420]
The `sortField` property is NOT inteded to sort data. It's just for showing the visual indicator (caret). I'd suggest we update our docs to read something like this (needs tweaking):

`sortField` — (Optional.) Allows consumer to programmatically control the visual indicator of a sorted field. This is useful if a consumer wants to programmatically sort the data, but also tell the grid column to display the caret. This property accepts a `ListSortFieldSelectorModel` value that contains a `fieldSelector` string to represent the current sort field and a descending `boolean` to indicate which direction the caret should display.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/424.
