### ISSUE TITLE
Document closing modal behavior without saving 

### ISSUE THREAD

**Issue by Blackbaud-MattGregg** [blackbaud/skyux2-docs#446]
I've had a few teams asking about and thinking they need to figure out how to ensure their users don't lose their work in a modal. I believe this is built into the system, but not yet documented for anyone to know about.

https://github.com/blackbaud/skyux-modals/pull/7

**Comment by Blackbaud-DeniseCisneros** [comment]
Checked in with @Blackbaud-TrevorBurch about this. Docs reflect this behavior, but the demo will be updated too to eliminate confusion.

**Comment by Blackbaud-MattGregg** [comment]
@Blackbaud-DeniseCisneros When you say it's reflected in the docs. Where does a designer/developer/other reader read about this behavior being baked into the component and what the behavior is? Is it in the Modal component page and I'm missing it or is it some place else? thx.

**Comment by Blackbaud-TrevorBurch** [comment]
This has been released and is on the docs site.
