### ISSUE TITLE
Update import instructions for color variables to reflect SKY UX 3

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#450]
The instructions at https://developer.blackbaud.com/skyux/design/styles/color to "import the color variables, add @import '~@blackbaud/skyux/dist/scss/mixins'; to the top of your SCSS file" need to be updated for SKY UX 3.

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/506
