### ISSUE TITLE
Progress indicator > Document item (step) statuses

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#463]
From @Blackbaud-AlexKingman "Now that we're setting all future steps to Incomplete, I feel like the docs should explicitly say this. It further enforces the fact that progress indicator is a forced sequential process."

See: https://github.com/blackbaud/skyux-progress-indicator/pull/17#discussion_r281807851

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/830.
