### ISSUE TITLE
Improve documentation on implications of using dataProvider on a list component

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#466]
https://developer.blackbaud.com/skyux/components/list/overview

Using the `dataProvider` inherently comes with some significant implementation differences. The docs don't necessarily make this very clear.

Important notes:

- Filtering / searching is now the responsibility of the consumer
- If consumer wants to enable multiselect toolbar, they'll also have to add logic to handle the "show only selected" checkbox, as this is also a filter.
- We should flesh out the demo to better demonstrate these points ☝️

**Comment by Blackbaud-DeniseCisneros** [comment]
Per Slack convo, would probably also make sense to add best practice info based on different use-cases
