### ISSUE TITLE
Assorted doc updates for SKY UX 3

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#470]
On the overview page (https://developer.blackbaud.com/skyux/learn/overview):
•	In the first bullet of What's New in SKY UX section, we need to change the second sentence. I think we should change “the SKY UX GitHub repo” to “multiple GitHub repositories that target different areas of development.
•	In the last paragraph of What's New in SKY UX section, we need to change the link. I think we should change “the SKY UX GitHub repo” to “multiple GitHub repositories that target different areas of development, but some features are for internal Blackbaud use only. To learn how we organize these packages, see the packages matrix.” And make “the packages matrix” a link to https://developer.blackbaud.com/skyux/contribute/packages.
•	In the second paragraph of Continuous integration section, we need to change the link. I think we should change “the SKY UX GitHub repo” to “our GitHub repositories.” And make “our GitHub repositories” a link to https://developer.blackbaud.com/skyux/contribute/packages.
•	In the last paragraph of SKY UX Host section, we need to change the link. I think we should change “the SKY UX GitHub repo” to “our GitHub repositories.” And make “our GitHub repositories” a link to https://developer.blackbaud.com/skyux/contribute/packages.
•	In GitHub section, we need to:
o	I’d change the header to “Contributions.”
o	In the first sentence, I think we should change “the SKY UX GitHub repo” to “our GitHub repositories that target different areas of development.”
o	I’d move the third sentence up to become the second sentence. And make “contribution guidelines” a link to https://developer.blackbaud.com/skyux/contribute/guidelines.
o	And in the current second sentence (and future third sentence), I’d change “lives in another GitHub repo, and” to “is also open source, so.”

In the Get started section (https://developer.blackbaud.com/skyux/learn/get-started):
•	In the second paragraph, change the second sentence. Delete “with the “documentation” label” and change “GitHub” to “documentation” and change the link to https://github.com/blackbaud/skyux2-docs.
•	In the Run Tests topic, for unit tests, is the guidance on `SkyAppTestModule` still accurate. I know there was some disagreement on this previously. Did the move to SKY UX 3 impact this?
•	In the Update Components topic, we need to rewrite the first bullet in the both bulleted lists. The package has changed to multiple packages. 
•	In the Static Assets topic, is the import location for `SkyAppAssetsService` still correct?

In the Reference section (https://developer.blackbaud.com/skyux/learn/reference):
•	In the second paragraph, we need to update the second sentence to reflect the multiple repos we now have.
•	In the Configuration topic, do we need to update the skyuxModules description in light of splitting up the components into separate repos for SKY UX 3? I think so. Based on a related (Blackbaud-internal) Slack thread at https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1555432771070800, I think we need to update this topic to explain something along the lines of "`skyuxModules` was the SKY UX 2 way of optionally limiting the SKY UX modules imported into your project.  SKY UX 3 goes a step further and _requires_ you to explicitly import all the SKY UX modules your application.  See the “Maintaining your application after migration” section of the SKY UX 3 migration guide for more info: https://developer.blackbaud.com/skyux-migration-guide/#maintaining-your-application-after-migration"
•	In the SKY UX CLI topic, I don’t see anything to update in the topics for individual commands in light of SKY UX 3. It’s probably a good idea to test the docs after migrating the docs site to SKY UX 3 though.
•	In the Additional Files topic under Configuration, in the last section’s code block, is the import location for `SkyAppConfig` still correct?
•	In the Additional Files topic under Configuration, in the step 5 code block, is the import location for `SkyAppConfig` still correct?
•	In the Template items topic, I think we need to create a new SPA and make sure the template items haven’t changed.
•	In the Template items topic, update the coverage folder entry to link to the guidelines on the site instead of the old repo. Also, remove the redundant “SKY UX” in the link text.
•	In the Libraries topic, in the last code block, is the import path for `SkyAppConfig` still correct?
•	In the Helpers topic, have the import paths for these helpers changed?
•	In the SkyAuthHttpClientModule topic under the Helpers topic, has the import path or anything else changed?
•	In the FAQ, the second item needs to be updated with language around the new location for components.
•	In the Resources topic, do we still need this section? If so, is any of it obsolete after more recent versions of Angular?

In the Accessibility section (https://developer.blackbaud.com/skyux/learn/accessibility):
•	In the opening paragraph, the link to SKY UX Builder is broken.
•	The known issues section needs to be updated to reflect the new structure of component repos. Right now, it points to the old repo.
•	The Get involved section needs to be updated to reflect the new structure of component repos. Right now, it points to the old repo.

**Comment by Blackbaud-DeniseCisneros** [comment]
Merged and completed in https://github.com/blackbaud/skyux2-docs/pull/512
