### ISSUE TITLE
Miscellaneous edits for Get started section

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#472]
•	Fix capitalization in the header
Prerequisites
•	This page should have action buttons. If users miss the left nav, the topic is a dead end.
•	In the first paragraph, I’d delete “to work with SKY UX” in the second sentence.
•	The second paragraph seems out of place here. It seems like it should be a section in Initial setup. Maybe an includes file since this info is already on the overview page. Maybe this belongs in the reference section as well.
SSL Certificate
•	I don’t see anything here
Initial Setup
•	I’d move the browser support info from the parent page to here.
Node.js
o	It looks like there is too much space in the bullet list. Check the styles there.
Basics
•	This page should have action buttons. If users miss the left nav, the topic is a dead end.
Create a SPA
•	Maybe we should remove the alert formatting and make the note and warning regular paragraphs.
•	In step 2, I’d change “the necessary items” to “the files and folders.” And I’d change “For more information about templates” to “For information about template items.”
Serve a project
•	I think the header should have “SPA” instead of “Project.”
Edit a project
•	I think the header should have “SPA” instead of “Project.”
Run tests
•	Also for unit tests, I’d combine the paragraphs in steps 1 and 2, respectively.
•	For e2e tests, we should pull the third paragraph before the first paragraph to make that recommendation before anything else.
Navigation
•	For internal links, in the paragraphs about parameters, we should include a link to the configuration property for this.
•	For external links, it looks like the first paragraph has “skyAppLink” when it should have “skyAppLinkExternal.”
Update CLI
•	I don’t see anything here
Advanced
•	This page should have action buttons. If users miss the left nav, the topic is a dead end.
Accessibility tests
•	I don’t see anything here other than the pending changes for the library path/link.
Accessibility analyzer
•	I’d change the note in the Manage accessibility rules section to a regular paragraph.
Entry components
•	I’d change the header to “Entry Components” and then add a page anchor for the tutorial with an “Add an entry component” header.
•	In the first paragraph, I’d change “that are generated” to “that you generate.”
•	In the second paragraph, I’d add “SPA’s” before “app-extras.module.ts.”
•	I’d add that page anchor after the second paragraph.
•	In the third paragraph, the “After you…” clause is from when this logically followed the series of tutorials in Basics. I’d update this to standalone. Maybe something like “The following tutorial walks you through the process to create a page with a SKY UX modal component and declare that component as an entry component.
•	In step 1, change “Return to the” to “Open your.”
•	I’d delete step 2 and add the last 2 sentences to step 1. I think we should make the name a code snippet too.
•	In step 3, I’d delete the first code snippet. And I’d change the part after the comma to “create an `index.html` file for the page.
•	I’d delete step 4 and pull it into the first line of step 3 before the code block.
•	In step 5, I’d change “Go to” to “In” and delete “and.”
•	In step 7, I’d rewrite to avoid the assumption that `skyux serve` might have been running. This is another hangover from when this was in a sequence of tutorials. I’m thinking “Save the changes and run `skyux serve` to view them in the SPA. The Modal entry appears…”
•	In step 8, I’d delete “new.” Actually, I’d change it to “In the `modal` folder, create a `modal-demo-context.ts` file, and add the following code:” … In the second paragraph, I’d change “to determine … from” to “to populate data based on the record where the form opens.”
•	In step 10, I’d change the opening to “In the `modal` folder, create a `modal-demo-launcher.component.ts` file to define the button component that launches the modal and its functionality, and add the following code:” … In the first paragraph after the code block, I’d change “The `import` entries import…” to “This imports…” and change the colon at the end to a period. … In the second bullet, I’d delete “from the template” and flip the second half of the sentence to use active voice. … In the fourth bullet, I’d also change “still need to create” to “will create.” … In the next-to-last paragraph, I’d delete the second “JavaScript.” … In the last paragraph, I’d change “portion” to “section.” (I actually don’t like this sentence, but I don’t know what else to change.)
•	In step 12, I’d change the opening to “In the `modal` folder, create a `modal-demo-launcher.component.html` file to serve as the template for the button component that launches the modal, and add the following code:”
•	In step 14, I’d change the opening to “In the `modal` folder, create a `modal-demo-form.component.ts` file to define the modal form component and its functionality, and add the following code:” … In the first paragraph after the code block, I’d change “The `import` commands import…” to “This imports…” and change the colon at the end to a period. … In the next-to-last paragraph, I’d delete the second “JavaScript.” … In the last paragraph, I’d change “portion” to “section.” (I actually don’t like this sentence, but I don’t know what else to change.)
•	In step 16, I’d change the opening to “In the `modal` folder, create a `modal-demo-form.component.html` file to serve as the template for the modal component, and add the following code:”
•	In step 17, change “Go to” to “In” and delete “and.” And  change “. At the top of the file” to “and.” I’d also pull the second paragraph into the first.
•	In step 18, I’d delete “the changes to.”
•	In step 19, I’d change “Return to” to “In” and delete “and.”
•	I’d reword step 20 to “Save the `index.html` file and any other files with unsaved changes.
•	In step 21, I’d delete the first sentence. I’d also pull this into step 20.
•	In step 22, I’d reword the first sentence to “In the browser, the default site displays our changes.
•	In step 23, I’d pull the step into the step 22. And I’d change “click” to “select” and delete “the” and “button.”
Localization
•	In the intro paragraph, I’d change “provides the capability” to “enables you.”
•	I’d make the alert a regular paragraph. I’d also flip the first sentence around to use active voice. (Also, maybe check with Bobby to see if there is any way to check if anyone is actually on a pre-1.14 version.)
Declare and reference localization strings
•	I’d also pull step 2 into step 1. I’d change “reuse” to “use.” I’d also change “Using” to “Use” and change the comma to “to” and add a comma before “and.”
•	In step 3, I’d change “using” to “with.” … And in the second bullet, I’d delete “in `@bskyux\i18n`” (or at least delete the stray “b”) and change “pull the string using `getString`” to “use `getString` to pull in the string.”
Use templated screen.
•	I’d pull step 2 into step 1. To make that work, I’d delete “in the string”
•	In step 3, I’d change “using” to “with.” … In the first bullet, I think “`string_name`” should just be “the string name” unformatted. … And in the second bullet, I’d delete “in `@skyux\i18n`” and change “pull the string using `getString`” to “use `getString` to pull in the string.”
Provide a custom locale provider
•	In the first paragraph, I think “through a different mechanism” should be “through a mechanism other than browser’s default.”
•	I don’t like the two lead-in paragraphs before the code blocks. They don’t communicate anything other than the filename. It would be better to describe what the code is doing. I don’t know what we’d say here, but might be worth following up. With Steve I think.
Module-level providers
•	In the first paragraph, I’d tweak the “similar to” wording. It’s very clunky.
•	In the second paragraph, I’d break out the first sentence into two sentences and pull in the third sentence: “The code sample below illustrates how to import module-level providers and services. It imports `DragulaService` and `DragulaModule` into the `app-extras.module.ts` file to provide a set of components and services that make drag and drop easier.”
•	I’d remove the alert, pull the content into the preceding paragraph, and delete “In the code sample.”
Pact testing
•	I don’t see anything here. (I only skimmed for potential changes for v3 because I know we have to revisit these docs.)
Route parameters
•	In the second paragraph, I think the “For example” sentence should be broken out into a new paragraph because right now it seems to modify the second sentence, as if it’s an example of the qualification instead of a qualification of the whole idea. I’d also remove the parentheses in the second sentence.
•	Step 9 in the procedure includes a code block with a reference to app-nav. Do we need to remove this?
Route wildcards
•	In the opening paragraph, I don’t think we need quotes around “404 page.”

**Comment by Blackbaud-JasonBoulware** [comment]
Could we add something like "Defined in `SkyAppLinkModule` in NPM package `@skyux/router`?" I had to do a little digging to figure this out

**Comment by blackbaud-johnly** [comment]
Thanks for the feedback, @Blackbaud-JasonBoulware. I've addressed most of the items in this issue in https://github.com/blackbaud/skyux2-docs/pull/503. Where are you looking for clarification on SkyAppLinkModule? Are you suggesting that we call out the NPM package in the Installation section of the Navigation documentation at https://developer.blackbaud.com/skyux/learn/get-started/basics/navigate-spa?

**Comment by Blackbaud-JasonBoulware** [comment]
Yes! I think making it a little more clear would be helpful for initial development.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/503.
