### ISSUE TITLE
Create animations for popover triggers

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#478]
Create animations to demonstrate the triggers for popovers. The prototype is at https://s69jnw.axshare.com. On the “click” prototype, you can click the inline help button to open the popover, then click outside of it to close it. On the “pageload” prototype, you can click the edit button, and a modal opens with the popover showing. Then you can click the related context menu button and the popover will close when the menu opens.

**Comment by Blackbaud-DeniseCisneros** [comment]
PR with the implemented videos https://github.com/blackbaud/skyux2-docs/pull/555

**Comment by Blackbaud-DeniseCisneros** [comment]
Merged and closed in https://github.com/blackbaud/skyux2-docs/pull/555
