### ISSUE TITLE
Update UA guidelines for empty-state WITHOUT call to action

### ISSUE THREAD

**Issue by Blackbaud-AdamFunderburk** [blackbaud/skyux2-docs#481]
A designer recently received feedback about a design, and the nature of that feedback revealed that these guidelines were interpreted as mandatory - EVERY empty state must follow this pattern. https://developer.blackbaud.com/skyux/design/guidelines/user-assistance#empty-state-help 

It may be beneficial to make the point that the empty-state pattern shown in these guidelines does not HAVE to be used. Some empty-states do not have applicable calls to action, such as when:

- It is unrealistic for a user to be responsible for resolving the empty-state (the Membership tile on a constituent record)
- The empty-state will be resolved through action elsewhere, and drawing attention to the object with the empty-state won't help the workflow

**Comment by Blackbaud-AdamFunderburk** [comment]
Draft examples to include alongside text
![image](https://user-images.githubusercontent.com/15896944/57880316-72970d80-77ec-11e9-894c-05aee07f69e1.png)

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/483.
