### ISSUE TITLE
Demo > repeater > include example of sky-repeater-item-context-menu component

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#487]
@blackbaud-johnly commented on [Thu Feb 14 2019](https://github.com/blackbaud/skyux2/issues/2311)

We received a request for to demonstrate `sky-repeater-item-context-menu` in the documentation. See Slack thread at https://blackbaud.slack.com/conversation/C3TQ4C0KG/p1550170704145100. (We can also expand the explanation of the component in the docs, but there are no public inputs or outputs to document at https://github.com/blackbaud/skyux-lists/blob/master/src/app/public/modules/repeater/repeater-item-context-menu.component.ts.)

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed in https://github.com/blackbaud/skyux2-demos/pull/3
