### ISSUE TITLE
Update docs to include newer method of mocking HttpClient

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux2-docs#488]
This page provides some guidance for unit tests an Angular service:
https://docs.blackbaud.com/learn-skyux/tutorials/testing/writing-service-tests

The technique shown in the docs mocks SkyAuthHttp (skyux2) - we should update the docs to include the newer skyux3 pattern using.

**Comment by Blackbaud-SteveBrush** [comment]
Closing this issue, and migrating the contents to a task on VSTS.
