### ISSUE TITLE
Update Installation section in component docs

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#489]
Coordinate with @Blackbaud-AdamFunderburk on new design for Installation section.

**Comment by Blackbaud-AdamFunderburk** [comment]
https://blackbaud.invisionapp.com/share/F9S5HAVZKQ6 for sm-md-lg mockups

**Comment by blackbaud-johnly** [comment]
Closing because we've migrated all docs to `docs-tools`, so all components have updated Installation sections as indicated in the mockups. We had discussions at one point about additional improvements, but that conversation didn't really gain traction and seems unlikely to be a priority at any time soon. We can always circle back to that idea later if necessary.
