### ISSUE TITLE
Grids & List View Grids > Update description for settingsKey property.

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#514]
Consumers have been expecting this property to return more types of grid settings than we currently support. Currently, we only return `selectedColumnIds` - should the docs reflect that? Also, there is a broken link in the current description.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/517.
