### ISSUE TITLE
Document "New" button for select field component

### ISSUE THREAD

**Issue by Blackbaud-DeniseCisneros** [blackbaud/skyux2-docs#516]
SHIELD team plans to contribute to the Select Field component with the addition of a "New" button. User story to track the team's work on that is below.

https://blackbaud.visualstudio.com/Products/_workitems/edit/1141641

**Comment by Blackbaud-AlexKingman** [comment]
For more information, see issue blackbaud/skyux-select-field#21

**Comment by Blackbaud-DeniseCisneros** [comment]
Duplicated. Merged and closed in https://github.com/blackbaud/skyux2-docs/pull/599
