### ISSUE TITLE
Installation instructions for @skyux/datetime don't mention peer dependencies

### ISSUE THREAD

**Issue by thatoddmailbox** [blackbaud/skyux2-docs#518]
The installation instructions for the [Datepicker](https://developer.blackbaud.com/skyux/components/datepicker#installation) component give the single command `npm install @skyux/datetime --save --save-exact`. However, this doesn't install the required peer dependency `@skyux/popovers`, and the Installation section on that page does not mention anything about that dependency, saying that you only have to run that command and add the export to your `app-sky.module.ts`. (though the broader "Use SKY UX Modules" instructions do mention watching out for peer dependency warnings)

**Comment by blackbaud-johnly** [comment]
Thanks, @thatoddmailbox. I am about to start work on updating the design/organization of Installation sections for all the component docs and am planning on calling out the need to watch for peer dependencies. I'll keep the issue you've filed in mind as I work on that docs update.

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/569
