### ISSUE TITLE
Modal components must be added to "entryComponents" list

### ISSUE THREAD

**Issue by thatoddmailbox** [blackbaud/skyux2-docs#522]
### Expected behavior
Adding a modal component, as explained in the [docs](https://developer.blackbaud.com/skyux/components/modal#demo), results in a modal that can be opened.

### Actual behavior
When I try to use `this.modal.open`, I receive an `Error: "No component factory found for LookupModalComponent. Did you add it to @NgModule.entryComponents?"` in the JavaScript console (where `LookupModalComponent` is the name of the modal component)

### Steps to reproduce
1. Add `lookup-modal.component.html`, `lookup-modal.component.ts`, `lookup-modal-context.ts` from the Files section below.
2. Try the following snippet:
```ts
var context = new LookupModalContext();
context.type = "user";

this.modal.open(LookupModalComponent, {
	providers: [{ provide: LookupModalContext, useValue: context }]
});
```
3. Get an error in the console, no modal

### Workaround
Adding `LookupModalComponent` to `entryComponents` in `app-extras.module.ts` does fix the problem. It's possible that this could just be a documentation issue and that the component is supposed to be added here?

#### lookup/lookup-modal-context.ts
```ts
export class LookupModalContext {
	public type: string;
}
```

#### lookup/lookup-modal.component.html
```html
<sky-modal [tiledBody]="true">
	<sky-modal-header>
		Search for {{ context.type }}
	</sky-modal-header>
	<sky-modal-content>
		<div>Content goes here</div>
	</sky-modal-content>
	<sky-modal-footer>
		<button class="sky-btn sky-btn-primary" type="button">
			OK
		</button>
	</sky-modal-footer>
</sky-modal>
```

#### lookup/lookup-modal.component.ts
```ts
import { Component } from "@angular/core";

import { SkyModalInstance } from "@skyux/modals";

import { LookupModalContext } from "./lookup-modal-context";

@Component({
	selector: "lookup-modal",
	templateUrl: "./lookup-modal.component.html"
})
export class LookupModalComponent {
	constructor(public context: LookupModalContext, public instance: SkyModalInstance) { }
}
```

**Comment by Blackbaud-TrevorBurch** [comment]
This is just a documentation issue. We will need to document this for both Modals and Flyouts

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/523.
