### ISSUE TITLE
Convert lists to new table styles

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#533]
Throughout the SKY UX docs site, update the bullet lists to emulate the new table style in the component docs. For example, convert the lists of options for CLI commands (https://developer.blackbaud.com/skyux/learn/reference/cli-commands) and other lists of data that would benefit from the new display that makes the content easier to read. (I'm breaking this out from https://github.com/blackbaud/skyux2-docs/issues/473 to address separately.)

**Comment by Blackbaud-DanMiller** [comment]
appears to be fixed by PR#77
