### ISSUE TITLE
Helpers page lists "SkyAuthHttpClientModule" as "SkyAuthClientHttpModule"

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux2-docs#537]
Just a small typo. It lists it correctly at the bottom of the bullet point but is incorrect in the import statement.

We have a contribution for this fix pending.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/536.
