### ISSUE TITLE
Document "New" button for select field component

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#545]
Document dev work under way in https://blackbaud.visualstudio.com/Products/_workitems/edit/1141641. Update the UX guidelines; see https://blackbaud.invisionapp.com/share/4GR2C4QSRUE#/screens.

**Comment by Blackbaud-DeniseCisneros** [comment]
Closing in favor of https://github.com/blackbaud/skyux2-docs/issues/595 where the PR for contribution is referenced.
