### ISSUE TITLE
Confirm component "custom" demo buttons don't match output

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux2-docs#547]
The demo shown here includes a "Custom confirm" button:
https://developer.blackbaud.com/skyux/components/confirm

The button launches a confirm dialog with options "1, 2, 3".  But the alert output showing what option you selected reads "foo", "bar", "baz".

![image](https://user-images.githubusercontent.com/15132359/55669500-34e6b280-5846-11e9-85e0-c6d640b2d664.png)

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed in https://github.com/blackbaud/skyux2-demos/pull/6
