### ISSUE TITLE
Document the --no-lint option

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#551]
`skyux watch` supports `--no-lint`. it's not [documented](https://developer.blackbaud.com/skyux/learn/reference/cli-commands/watch).

I'm not sure if other commands accept that option.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-BobbyEarl, are there other commands that accept that flag? Like maybe `test`? ... Also, I assume the description for this flag should be something along the lines of "Prevents the command from validating the TypeScript code in the files in the src folder against the rules specified by the tslint.json file in the SKY UX Builder repo." Does that sound about right?

**Comment by blackbaud-johnly** [comment]
Oh, and thanks for filing this, @Blackbaud-ColbyWhite!

**Comment by Blackbaud-BobbyEarl** [comment]
Technically, `build-public-library`, `lint`, `test`, `watch`, and `pact` all reference [`ts-linter` utility class](https://github.com/blackbaud/skyux-sdk-builder/blob/b9db9dbc458f648a7c9c747548e6af350745a39b/cli/utils/ts-linter.js).

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/552.
