### ISSUE TITLE
Sectioned forms component demo doesn't work on StackBlitz

### ISSUE THREAD

**Issue by Blackbaud-TimothyWittig** [blackbaud/skyux2-docs#553]
### Expected behavior
Expected the StackBlitz demo to work [here](https://developer.blackbaud.com/skyux/components/sectioned-form#demo).

### Actual behavior
The demo throws an in the console.

### Steps to reproduce
Navigate to StackBlitz demo on component documentation page [here](https://developer.blackbaud.com/skyux/components/sectioned-form#demo).

### Severity
Low

### Impact
Can't use StackBlitz to reproduce a separate bug I wanted to create an issue for.

**Comment by Blackbaud-SteveBrush** [comment]
We get this error: `No provider for SkyMediaQueryService!`
