### ISSUE TITLE
Update grid docs to call out required ID and property

### ISSUE THREAD

**Issue by Blackbaud-DeniseCisneros** [blackbaud/skyux2-docs#558]
Update docs to be more clear about required ID and property for `sky-grid`.

"Each item requires an id and a property that maps to the field or id property of each column in the grid."

**Comment by blackbaud-johnly** [comment]
Based on team discussion, we will play around with highlighting the relevant table in the current location within the table and also with adding an alert above the table to see what works best. In addition, we will look into adding a code comment to the demo to call this out there.

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and fixed in https://github.com/blackbaud/skyux2/pull/2373

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and merged in https://github.com/blackbaud/skyux2-demos/pull/8
