### ISSUE TITLE
Update select field docs to include missing properties

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#563]
In https://developer.blackbaud.com/skyux/components/select-field#skyselectfield-properties, the properties don't match up with the properties in the demo. Based on https://github.com/blackbaud/skyux-select-field/blob/master/src/app/public/modules/select-field/types/select-field.ts, we are missing an `index` property, but that code doesn't include the `description` property from the demo. Apparently, that demo has something to do with another component. (List view grid maybe? I can't remember.) We need to update the documentation to make sure the properties are correctly documented in the correct location.

@Blackbaud-AlexKingman looked into this, so I will coordinate with him on how/where to document the `description` property. (Feel free to add the info directly to the issue if that's easier.)

**Comment by blackbaud-johnly** [comment]
From the email about this:

It looks like `description` gets passed through to the list-view-checklist component, which we do have documented (https://developer.blackbaud.com/skyux/components/list/checklist#list-view-checklist-properties). Now, whether or not that was intentional or just a happy coincidence, I’m not sure. It doesn’t appear that we have any test coverage around this particular property inside of select-field.

**Comment by Blackbaud-DeniseCisneros** [comment]
Completed and merged in https://github.com/blackbaud/skyux2-docs/pull/636
