### ISSUE TITLE
FIlter UX guidelines incorrectly states use dropdown

### ISSUE THREAD

**Issue by Blackbaud-MattGregg** [blackbaud/skyux2-docs#566]
The UX guidelines for the Filter component incorrectly states a dropdown can be used as a filter selection component. This is not the case and confuses the already problematic dropdown component. 
https://developer.blackbaud.com/skyux/components/filter#ux-guidelines

"Use inline filters to apply up to three simple filters to a list or tile. This pattern works well with checkboxes or dropdowns, but not with complex selection controls."

dropdowns should be removed and replaced with HTML select input. Potentially the SKY UX select field single mode could be used there too.

**Comment by blackbaud-johnly** [comment]
Thanks for filing, @Blackbaud-MattGregg. I created https://github.com/blackbaud/skyux2-docs/pull/567 to address this.
