### ISSUE TITLE
List > Update selectedIds property

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#571]
Related change: blackbaud/skyux-list-builder#57

Here's what I would suggest:
https://developer.blackbaud.com/skyux/components/list/overview#list-properties
Update property `selectedIds` to read:
> Specifies a set of selected IDs to use with checklist or multiselect grids. The ID matches the `id` property of the `data` object. Any ID values not provided will be de-selected. Acceptable values: `Observable Array of strings or Array of strings`.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/573.
