### ISSUE TITLE
Grids > Add property for selectedRowIds

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#574]
Add the following property:
`selectedRowIds`

Description:
> Specifies a set of selected row IDs to use with the grid. The ID matches the `id` property of the `data` object. Any ID values not provided will be de-selected. Acceptable values: `Array of strings`.

Optional.

**Comment by blackbaud-johnly** [comment]
Looks like this is based on changes to the selectedIds property, which I tweaked slightly in ://github.com/blackbaud/skyux2-docs/pull/573. The changes here should probably line up with those.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/578.
