### ISSUE TITLE
Repeater > Add property for isActive

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#575]
Add the following property:
`isActive`

Description:
> Indicates whether the repeater item shows an active state. This is used in conjunction with the split view component to show which item in the repeater is currently being edited. This property accepts `boolean` values.

Optional.

Default = `false`

We should also update the demo to show how to use this.

**Comment by Blackbaud-AlexKingman** [comment]
I'm not 100% on including the bit about the split-view component. Maybe we leave that out?

**Comment by blackbaud-johnly** [comment]
I went ahead and set up the docs at https://github.com/blackbaud/skyux2-docs/pull/577. I kept the bit about the split view component but reworded it as an example to try to make it a more natural fit. We can always remove that sentence if it still doesn't work, but I think it's valuable in that it provides context on what this property is useful for.

**Comment by Blackbaud-DeniseCisneros** [comment]
OMG, John, sorry! I had an old tab opened and didn't see you had assigned it to yourself. Deleting my PR.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/577.
