### ISSUE TITLE
repeater demo should use context menu rather than default dropdown

### ISSUE THREAD

**Issue by Blackbaud-ToddRoberts** [blackbaud/skyux2-docs#579]
Repeater demo currently has a regular dropdown button on the left side of the repeater row. These should be context menu style instead.

![image](https://user-images.githubusercontent.com/13765813/61487557-314de600-a974-11e9-976b-a36be006340f.png)

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and fixed in https://github.com/blackbaud/skyux2/pull/2373

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and merged in https://github.com/blackbaud/skyux2-demos/pull/8
