### ISSUE TITLE
Update phone field docs to reflect ability to automatically change country through the dial code

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#588]
Update docs to reflect work in https://github.com/blackbaud/skyux-phone-field/pull/16. The pending changelog announcement says that "Added the ability for the phone field component to automatically switch countries based on a given dial code" and we need to update the docs to to call out that if the user types `+` followed by the international dial code, then the country automatically switches to the country associated with that dial code.

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed and merged in https://github.com/blackbaud/skyux2-docs/pull/608
