### ISSUE TITLE
Document new input for repeater component

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#590]
For https://github.com/blackbaud/skyux-lists/pull/51, update the repeater docs to include entries for the `activeIndex` property. 

Note that in the changes, it looks like the `inlineFormConfig` and `inlineFormTemplate` inputs and the `inlineFormClose` output may also have changed.

**Comment by Blackbaud-AlexKingman** [comment]
@blackbaud-johnly 

> Note that in the changes, it looks like the inlineFormConfig and inlineFormTemplate inputs and the inlineFormClose output may also have changed.

No docs changes needed for these properties. Those changes were simply reordering to be in compliance with our code standards. These properties still work the same as before.

**Comment by Blackbaud-AlexKingman** [comment]
Suggestion for `activeIndex`:

Specifies the index of the active repeater item. Only one item can be active at a time. This property accepts `number` values. Optional. Default: `undefined`

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed and merged in https://github.com/blackbaud/skyux2-docs/pull/612
