### ISSUE TITLE
Document `SKY_AUTH_DEFAULT_PERMISSION_SCOPE`

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#596]
Pull request: https://github.com/blackbaud/skyux-http/pull/32

**Comment by Blackbaud-DeniseCisneros** [comment]
Added and merged in https://blackbaud.visualstudio.com/Products/_git/skyux-spa-engineering-system-docs/pullrequest/69087?_a=overview
