### ISSUE TITLE
Document router commands for permalink property in action button component

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#606]
Update the docs at https://developer.blackbaud.com/skyux/components/action-button#skyactionbuttonpermalink-properties to address an internal question about the available options for the "commands property to specify router commands." ... Filing this issue based on internal feedback. The internal-only Slack thread where the question was raised is at https://app.slack.com/client/T02BBN218/C3TQ4C0KG/thread/C3TQ4C0KG-1565364685.448900.

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed and merged in https://github.com/blackbaud/skyux2-docs/pull/620
