### ISSUE TITLE
List > Update `data` property to better explain how the `id` property effects multiselect

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#609]
Suggestion:

> Specifies the data to display. Must provide `data` or `dataProvider`. Acceptable values: `Observable Array` or `Array`. To update data in your view outside of a `dataProvider`, you must use an observable instead of a static array). Each row requires an `id` property that will be used when managing selected items with the `selectedIds` input property and the `selectedIdsChange` event. If an `id` is not provided, the list will automatically generate one for you.

Related: #571

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/611.
