### ISSUE TITLE
Add/update CONTRIBUTING.md files for all repos

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#618]

**Comment by Blackbaud-BobbyEarl** [comment]
I imagine this file to be short and sweet.  Perhaps, something like...

```
Thank you for your interest in contributing!

Please see our [contributing guide information](https://developer.blackbaud.com/skyux/contribute/guidelines) for detailed instructions on how to contribute to SKY UX.
```

**Comment by Blackbaud-BobbyEarl** [comment]
Once we've finalized the file, I should be able to re-use my previously built automation to push this to all our repos, unless someone just really wants to do it manually.

Approval and merging would still need to happen manually.

**Comment by blackbaud-johnly** [comment]
Addressed in various PRs, including https://github.com/blackbaud/skyux2-docs/pull/655.
