### ISSUE TITLE
List-builder demo > add example for using filters with data provider

### ISSUE THREAD

**Issue by Blackbaud-AlexKingman** [blackbaud/skyux2-docs#653]

**Comment by Blackbaud-TrevorBurch** [comment]
In `1.3.1`. @Blackbaud-DeniseCisneros assigning to you to finish pulling this in when you finish the rest of the docs updates.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-demos/pull/23.
