### ISSUE TITLE
Document properties of ListDataRequestModel in the list component docs

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#654]
The properties in `ListDataRequestModel` are public, and in https://github.com/blackbaud/skyux2-docs/pull/648 we call out that the consumer is responsible for those properties if they use `dataProvider` instead of `data`. We need to add a new section to document these properties, and we should link to it form the `dataProvider` property.

**Comment by Blackbaud-DeniseCisneros** [comment]
Merged and closed in https://github.com/blackbaud/skyux2-docs/pull/692
