### ISSUE TITLE
Document Fuzzy Date Directive

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#656]
Implementation issue: https://github.com/blackbaud/skyux-datetime/issues/74

**Comment by blackbaud-johnly** [comment]
I changed the impact to medium because that's what Todd put on https://github.com/blackbaud/skyux2-docs/issues/657.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/659.
