### ISSUE TITLE
Fix UI wonkiness in alert StackBlitz demo

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#663]
After opening the StackBlitz alert demo, the dropdown menu only shows 3 of the 4 options, and it chops them off from the left.
![image](https://user-images.githubusercontent.com/7850105/65198858-b035cc80-da52-11e9-8123-e9652f54f595.png)

**Comment by Blackbaud-AlexKingman** [comment]
The demo has been updated and this is no longer an issue.
