### ISSUE TITLE
Document required property for radio group, checkbox, and single-file attachment

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#674]
https://github.com/blackbaud/skyux-forms/pull/77
https://github.com/blackbaud/skyux-forms/pull/78

**Comment by Blackbaud-AlexKingman** [comment]
@blackbaud-johnly re-evaluating this approach. We may have a way to automate this by going off the native HTML attributes and Angular's native reactive form settings. Going to put this on hold until we decide if the documentation is necessary.

**Comment by Blackbaud-AlexKingman** [comment]
I confirmed we're replacing this with the `required` attribute. I'll change the title of this story to reflect that.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/759.
