### ISSUE TITLE
Add design guidelines for launching confirm components from modals

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#684]
Related issue: https://github.com/blackbaud/skyux-modals/issues/69

**Comment by Blackbaud-MichaelCollier** [comment]
Will revisit and document if consuming teams need more direction for these interactions.

**Comment by blackbaud-johnly** [comment]
The Sub-forms section at https://developer.blackbaud.com/skyux/design/guidelines/form-design#field-layout provides some guidance on opening modals from within modals.
