### ISSUE TITLE
Document that highlight directive can't be placed on a template element.

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux2-docs#694]
For blackbaud/skyux-indicators#36

The highlight direct can not be placed on `ng-template`, `ng-content` or `ng-container` tags. It must be placed on elements which truly have content.

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed and closed in https://github.com/blackbaud/skyux2-docs/pull/777
