### ISSUE TITLE
Add `barebones` as another `--template` type for `skyux new`

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#695]
Here: https://developer.blackbaud.com/skyux/learn/reference/cli-commands/new#options

See https://github.com/blackbaud/skyux-sdk-template/issues/6

**Comment by Blackbaud-DeniseCisneros** [comment]
Fixed and closed in https://github.com/blackbaud/skyux2-docs/pull/743
