### ISSUE TITLE
Document `frameOptions` configuration option 

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#697]
See https://github.com/blackbaud/skyux-config/pull/29.

Add an entry to the SKY UX docs at https://developer.blackbaud.com/skyux/learn/reference/configuration:
```Specifies an `X-Frame-Options` value for SKY UX Host HTTP headers to set security preferences for the SPA's embedded iframes. This property is for internal Blackbaud use only.```

Add an internal-only link after the last sentence to the Engineering System docs, and create a new "Security preferences for embedded iframes" entry in the SPAs section at https://host.nxt.blackbaud.com/engineering-system-docs/learn/spa.

**Comment by blackbaud-johnly** [comment]
For reference for the Engineering System docs topic, here's Steve's original description of the property:
```"description": "Specifies a value for `X-Frame-Options` that will be applied to the SKY UX Host HTTP headers. This value allows SPAs to set their own security preferences for embedded iframes. Possible values include \"sameorigin\", \"deny\", \"blackbaud\", or \"allow-from https://www.example.com\". Setting this value to \"blackbaud\" will only allow iframes to set their `src` attribute to whitelisted Blackbaud domains."```

**Comment by Blackbaud-DeniseCisneros** [comment]
Addressed and merged in https://github.com/blackbaud/skyux2-docs/pull/833
