### ISSUE TITLE
Document `itemTemplate` attribute for text expand repeater component

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#707]
Feature pull request: https://github.com/blackbaud/skyux-layout/pull/48

**Comment by blackbaud-johnly** [comment]
See https://github.com/blackbaud/skyux-layout/pull/48.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/723.
