### ISSUE TITLE
Update documentation for expand all/collapse all functionality

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#725]
This is related to a team conversation about sticky settings and possible updates there plus calling out not to adjust the config.

From Paul: "What we need to document is a) the new expand all/collapse all feature of tile dashboards once that’s been added, and b) the caveat of not updating the config object passed to the tile dashboard after the dashboard’s already been rendered, because the results of doing so will be unpredictable at best."

**Comment by Blackbaud-TrevorBurch** [comment]
@blackbaud-johnly @Blackbaud-DeniseCisneros it appears that this issue has been partially addressed but not fully. It appears that we have documented "a" in Paul's advice but not "b". Unless I'm overlooking something on the page.
