### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#756]
Audit the text content of the SKY UX error messages (https://developer.blackbaud.com/skyux/components/error) to make sure they follow SCD guidelines. A project is under way to revamp the images in the error messages, so we should take this as an opportunity to make any necessary changes to the text as well.

**Comment by Blackbaud-AdamFunderburk** [comment]
As luck would have it, someone is currently drafting UX content for the Error component now.

**Comment by blackbaud-johnly** [comment]
Closing this after coordinating with UX and Marketing on new messages and handing off the final versions.
