### ISSUE TITLE
Fix dropdown demo so that options don't float over omnibar

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#790]
When scrolling down the dropdown comonent's documentation page with the dropdown menu options exposed, the menu appears over the omnibar. This issue was identified on the internal #1bb-skyux-apps channel. The suggested solution was that the z-index needs to be tweaked.

**Comment by Blackbaud-SteveBrush** [comment]
Closing because this is behaving as expected; a dropdown menu has z-index preference so that menu items are accessible on small windows.
