### ISSUE TITLE
Treeview component docs

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux2-docs#793]
Just some suggestions for the treeview component docs:
https://developer.blackbaud.com/skyux/components/tree-view

1) I get the idea behind the reminder alert, but I would have preferred 2 "installation commands" statements (with copy) instead of this presentation:
![image](https://user-images.githubusercontent.com/15132359/72185032-ce3b8a00-33bf-11ea-9711-1449ac71fc35.png)

2) There's no mention of installing the SkyAngularTreeModule module, similar to what we do with other components, ex:  "After installation, you need to make any exports from SkyActionButtonModule available to your SPA by adding the module....".  I like that reminder sentence, and think we ought to add it for the tv as well.

3) I think the SKYUX treeview component docs would benefit from a reminder about importing the TreeModule - I know we're trying to strike a balance of not documenting another company's component, but I bet any dev walking up to this component would probably forget that step.  So I think even a simple "don't forget to import TreeModule" would help.  As my first attempt in using this component, I had to search through other BB source code to find any example of what needed importing/exporting in app extras:
https://blackbaud.visualstudio.com/Products/_git/skyux-spa-org-profile?path=%2Fsrc%2Fapp%2Fapp-extras.module.ts&version=GBmaster&line=63&lineEnd=64&lineStartColumn=1&lineEndColumn=1&lineStyle=plain

**Comment by Blackbaud-AlexKingman** [comment]
Great suggestions!

I believe #2 has been addressed now that we're in the new docs platform. As for the other two items, I feel like a "Dependencies" section would be a potential solution? Its not something we currently have a pattern for, but it could easily addressed extra package installations (#1 above) as well as proper module imports (#3 above). This is more of a long-term solution, but maybe we can do something quicker in the short-term?

@blackbaud-johnly curious on your thoughts here.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-AlexKingman and I talked about this, and we already have https://github.com/blackbaud/skyux-docs-tools/issues/72 in place, which would address this, and the work started on this earlier this year. Not sure what the status is, but we're going to follow up on that before trying any short-term workarounds.

**Comment by blackbaud-johnly** [comment]
This is still blocked by https://github.com/blackbaud/skyux-docs-tools/issues/72. We should migrate this issue over to ADO since that's where we're managing docs issues now.

**Comment by blackbaud-johnly** [comment]
Closing to manage this issue in ADO.
