### ISSUE TITLE
Values for skyux serve --browser are incorrect

### ISSUE THREAD

**Issue by Blackbaud-JasonBodnar** [blackbaud/skyux2-docs#804]
The docs for the `--browser` argument of `skyux serve` are incorrect:

> the available values are chrome, edge, firefox, iexplore, and safari

From the `open` command that is used to start the browser:

> The app name is platform dependent. Don't hard code it in reusable modules. For example, Chrome is `google chrome` on macOS, `google-chrome` on Linux and `chrome` on Windows.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/809.
