### ISSUE TITLE
"Form Design" page says inline form is not completed

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux2-docs#806]
The docs at https://developer.blackbaud.com/skyux/design/guidelines/form-design say 

> An inline panel (the component is not developed yet) is appropriate for simple forms that meet the following criteria:

That link points to https://github.com/blackbaud/skyux-inline-form/issues/2 which is closed.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/811.
