### ISSUE TITLE
Missing skyDate pipe docs

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#807]
There doesn't appear to be docs for the `skyDate` pipe. i found the `skyNumeric` pipe in the component documentation, but no `skyDate`. 

## Impact
devs are thinking they have to manually do locale stuff themselves b/c they either don't know the pipe exists or aren't familiar with how to pass the parameters they see in the source code in the angular pipe syntax.

**Comment by blackbaud-johnly** [comment]
We already have an issue at https://github.com/blackbaud/skyux2-docs/issues/335. (The title was a little off and may not have come up on a search for "skyDate pipe," so I've updated it.) ... I'll be working with @Blackbaud-SteveBrush and @Blackbaud-AlexKingman to get the skyDate pipe documented.
