### ISSUE TITLE
Documentation around @skyux/http HttpInterceptor for resolving AKS service URLs

### ISSUE THREAD

**Issue by ThomasOrtiz** [blackbaud/skyux2-docs#837]
[Slack Link from Jon Bell](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1565101339341400?thread_ts=1565101339.341400&cid=C3TQ4C0KG)

The http interceptor to resolve AKS service urls is only documented in Slack from what I've seen.

Potential Places
- [spa-authenticated-calls](https://docs.blackbaud.com/engineering-system-docs/learn/spa/spa-authenticated-calls)
- [spa-connection-strings](https://docs.blackbaud.com/engineering-system-docs/learn/spa/spa-connection-strings)
- [@skyux/http/readme.md](https://github.com/blackbaud/skyux-http#readme)

**Comment by blackbaud-johnly** [comment]
This update will be for the internal docs on authenticated calls.

**Comment by blackbaud-johnly** [comment]
Need to migrate this over to ADO and follow up with Paul or Steve on what to document here.

**Comment by Blackbaud-KerryCampbell** [comment]
Moved to [ADO issue](https://dev.azure.com/blackbaud/Products/_workitems/edit/1743324)
