### ISSUE TITLE
Update docs to reflect changes in dependencies

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#838]
https://github.com/blackbaud/skyux-sdk-builder/pull/211 highlights several breaking changes. We need to search the SKY UX site and Engineering System docs for references to items that reference deprecated dependencies. For example, https://developer.blackbaud.com/skyux/learn/get-started/advanced/include-static-assets includes `@angular/http` in a code block, and https://developer.blackbaud.com/skyux/learn/reference/configuration includes `SkyAuthHttp` in a configuration property description. Need to check the docs for references like this and coordinate with @Blackbaud-SteveBrush on how to update the docs.

**Comment by Blackbaud-DanMiller** [comment]
On hold until builder 4 is actually ready for release.

**Comment by blackbaud-johnly** [comment]
Need to migrate this over to ADO.

**Comment by blackbaud-johnly** [comment]
Closing to manage this work in ADO.
