### ISSUE TITLE
Split-view docs - articulate default drawer width behavior

### ISSUE THREAD

**Issue by Blackbaud-BenLambert** [blackbaud/skyux2-docs#851]
In the docs for the split-view component, it would be good to mention what the default behavior is if no value for `width` is provided:
https://developer.blackbaud.com/skyux/components/split-view#split-view-drawer-properties

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/853. Thanks, @Blackbaud-BenLambert!
