### ISSUE TITLE
Document `sky-code` component

### ISSUE THREAD

**Issue by Blackbaud-BobbyEarl** [blackbaud/skyux2-docs#861]
Original pages in Stache:

- https://developer.blackbaud.com/stache/components/code-block
- https://developer.blackbaud.com/stache/components/code

Looks like only the `code-block` documentation was migrated to our current docs:

- https://developer.blackbaud.com/skyux/components/code-block

**Comment by Blackbaud-DeniseCisneros** [comment]
Merged and closed in https://github.com/blackbaud/skyux2-docs/pull/905

**Comment by Blackbaud-BobbyEarl** [comment]
Let me know if you need help with a PR in to `sky-skysp-svc` @Blackbaud-DeniseCisneros.
