### ISSUE TITLE
Clarify Fluid Grid docs so that it is more clear what the default values for a column's "screen..." properties

### ISSUE THREAD

**Issue by Blackbaud-AnthonyDuncan** [blackbaud/skyux2-docs#872]
### **Current View**
Notice that the default value for the various "screen..." properties is blank. The description itself contains that default value and is easy to miss:
![image](https://user-images.githubusercontent.com/51380185/77093723-62862680-69d9-11ea-9e04-6ce74859a33c.png)

### **Proposed View**
Propose removing the sentence with the default value from the description and instead move it to the appropriate line of the default value column:
![image](https://user-images.githubusercontent.com/51380185/77093551-1dfa8b00-69d9-11ea-9e87-2f681d6a5fb9.png)

### **Status**
A PR can be ready very quickly assuming the proposed view is considered acceptable. Any and all feedback is appreciated.

**Comment by Blackbaud-SteveBrush** [comment]
@Blackbaud-AnthonyDuncan Thanks for the issue! We'll add a default value of `12` in the first row, and leave the descriptions the same for the other rows.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/874.
