### ISSUE TITLE
Create internal docs on how to pull user info out of out of bbAuth token

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#884]
Need to add internal docs to Engineering System for `SkyAuthTokenProvider`. @Blackbaud-BobbyEarl recommended adding it as a sibling to https://docs.blackbaud.com/engineering-system-docs/learn/spa/spa-authenticated-calls or somewhere in that section. 

The Slack thread at https://app.slack.com/client/T02BBN218/C3TQ4C0KG/thread/C3TQ4C0KG-1585683969.135400 discusses this. From @Blackbaud-PaulCrowder in that thread: 

"There is a first-class way now. Inject SkyAuthTokenProvider and call its getDecodedContextToken(). That will fetch a token in the context of your current environment or legal entity and return a decoded token."

Also:
"Also let TypeScript infer the type of token as opposed to typing it as any , since there is an interface that first-classes all the JWT properties."

**Comment by Blackbaud-SteveBrush** [comment]
We talked offline and decided to put this info here: https://docs.blackbaud.com/engineering-system-docs/learn/spa/spa-authenticated-calls

**Comment by Blackbaud-DeniseCisneros** [comment]
PR in ADO
https://dev.azure.com/blackbaud/Products/_git/skyux-spa-engineering-system-docs/pullrequest/104928

**Comment by Blackbaud-DeniseCisneros** [comment]
ADO PR Merged
