### ISSUE TITLE
Update Omnibar docs for new concepts

### ISSUE THREAD

**Issue by Blackbaud-TrevorBurch** [blackbaud/skyux2-docs#890]
We should make some tweaks to the "Configuring omnibar" page

1. We should remove the "Examples" section
2. Mention that when configuring the omnibar in a SPA that the options will need to go in the `omnibar` section of `skyuxconfig.json`
3. Add a mention that global navigation is the preferred method of registering navigation and add a link to our internal docs around this. This should be mentioned in regards to the `nav` option which is the secondary way of specifying navigation.

**Comment by Blackbaud-DeniseCisneros** [comment]
Merged in https://blackbaud.visualstudio.com/Products/_git/skyux-spa-omnibar-docs/pullrequest/104474
