### ISSUE TITLE
toggle demo and code example don't match

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#909]
The demo for the [toggle docs](https://developer.blackbaud.com/skyux-forms/docs/toggle-switch;docs-active-tab=development) doesn't match the code example and its corresponding [stackblitz](https://stackblitz.com/run?file=src%2Fapp%2Ftoggle-switch-demo.component.html).

**Comment by Blackbaud-AlexKingman** [comment]
The stackblitz demos aren't always intended to match the behavioral demo at the top of the page. You'll see more of these examples as we roll out more of the newer docs pages. If you're looking for additional demos for a particular component, we can certainly talk about what you'd need to be shown here - just let us know. Closing the issue for now - please feel free to reopen if you have more thoughts.
