### ISSUE TITLE
Name of phone field event is wrong `selectedCountryChanged` instead of `selectedCountryChange`

### ISSUE THREAD

**Issue by Blackbaud-DanGrochmal** [blackbaud/skyux2-docs#927]
Line 151 of https://github.com/blackbaud/skyux2-docs/blob/master/src/app/components/phone-field/index.html

**Comment by blackbaud-johnly** [comment]
Thanks for pointing this out, @Blackbaud-DanGrochmal! I'll get a fix in shortly.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/928.
