### ISSUE TITLE
Document how to set grid column alignment

### ISSUE THREAD

**Issue by Blackbaud-SteveBrush** [blackbaud/skyux2-docs#929]
Related pull request: https://github.com/blackbaud/skyux-grids/pull/114

@Blackbaud-ToddRoberts commented on [Fri May 29 2020](https://github.com/blackbaud/skyux-grids/issues/129)

We recently added a property for text alignment on grid columns, but it is not documented yet.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/933.
