### ISSUE TITLE
Document missing grid column properties

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#934]
The `type` and `excludeFromHighlighting` properties for the grid column component aren't included in the docs at https://developer.blackbaud.com/skyux/components/grid#grid-column-properties.

**Comment by blackbaud-johnly** [comment]
The `excludeFromHighlighting` property "stops columns form having their contents highlighted when searching," but I don't know what the use case is.

**Comment by Blackbaud-AlexKingman** [comment]
`type` should be @internal. I'll add a description for `excludeFromHighlighting` though.
