### ISSUE TITLE
Documentation for flyout default width is incorrect

### ISSUE THREAD

**Issue by blackbaud-GavinNicol** [blackbaud/skyux2-docs#956]
### Expected behavior

Documentation for flyout default width should be half the screen size.

### Actual behavior

Documentation shows that flyout default width is 500px.

The code located here shows that the default width if none is provided is actually half the window size. https://github.com/blackbaud/skyux-flyout/blob/master/src/app/public/modules/flyout/flyout.component.ts

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/957.
