### ISSUE TITLE
Implement SKY UX Action buttons across SKY UX docs

### ISSUE THREAD

**Issue by Blackbaud-DeniseCisneros** [blackbaud/skyux2-docs#972]
After adding search functionality for the SKY UX action buttons (Issue https://github.com/blackbaud/skyux-layout/issues/96), the action buttons used throughout the SKY UX site should be updated to use the SKY UX action buttons instead of the Stache action buttons.

**Comment by blackbaud-johnly** [comment]
Closing for now but can reopen if this resurfaces as a priority.
