### ISSUE TITLE
Clarify the frameOptions option

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#976]
The doc around this option is a bit misleading; specifically how it is has been brought up in a [couple](https://blackbaud.slack.com/archives/C016KFABF0X/p1595268941154400) [threads](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1591726412422600).

Also, the doc does not mention what happens when you leave off `frameOptions` completely.

**Comment by Blackbaud-MattWalsh** [comment]
PR submitted https://blackbaud.visualstudio.com/Products/_git/skyux-spa-engineering-system-docs/pullrequest/120489?_a=files

**Comment by blackbaud-johnly** [comment]
Need to dig into the Slack threads on this and look into more updates to address Colby's questions. Based on side conversations with him, Matt's PR did not address all of his concerns with these docs.

**Comment by Blackbaud-ColbyWhite** [comment]
it looks like the `blackbaud` option results in the following header:
```
Content-Security-Policy | frame-ancestors https://*.blackbaud.com https://*.blackbaud-dev.com https://*.blackbaud-test.com
```

the actual value would be useful in the doc. or a link to where the values are hardcoded. it may also be useful to note that this prevents `localhost` embedding or potentially any other local dev if the embedding app is _not_ a SKY UX SPA.

**Comment by blackbaud-johnly** [comment]
Another internal Slack thread on this: https://app.slack.com/client/T02BBN218/C3TQ4C0KG/thread/C3TQ4C0KG-1596489836.117900.

**Comment by Blackbaud-KerryCampbell** [comment]
Moved to [ADO issue](https://dev.azure.com/blackbaud/Products/_workitems/edit/1743317)

**Comment by Blackbaud-ColbyWhite** [comment]
@Blackbaud-KerryCampbell, fyi, by closing the github issue you also closed the ado issue. i assume that wasnt intentional. j/ a heads up.
