### ISSUE TITLE
default for --checkout options incorrect

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#981]
https://developer.blackbaud.com/skyux/learn/reference/cli-commands/new

the listed default for --checkout is `master`, but the alert at the bottom of the page indicates that `[MAJOR_VERSION].x.x` is the actual default. experience seems to indicate the latter. see [slack thread](https://blackbaud.slack.com/archives/C3TQ4C0KG/p1595876826451200) for more info.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/983.
