### ISSUE TITLE
Missing searchUrl from possible omnibar config

### ISSUE THREAD

**Issue by Blackbaud-ColbyWhite** [blackbaud/skyux2-docs#987]
Neither the [omnibar docs](https://docs.blackbaud.com/omnibar-docs/learn/configuring) nor the [global nav](https://docs.blackbaud.com/engineering-system-docs/learn/spa/spa-global-navigation) inidicate what that a [`omnibar.nav.services.searchUrl`](https://dev.azure.com/blackbaud/Products/_search?action=contents&text=repo%3Askyux*%20file%3Askyuxconfig.json%20omnibar%20searchUrl&type=code&lp=code-Project&filters=ProjectFilters%7BProducts%7D&result=DefaultCollection%2FProducts%2Fskyux-spa-lists%2FGBmaster%2F%2Fskyuxconfig.json) is possible in `skyuxconfig.json`. it also seems that in non-stache cases, the preferred method is through [skyux-ia](https://dev.azure.com/blackbaud/Products/_git/skyux-ia?path=%2Fservices%2Fengsys.yaml&version=GBmaster&_a=contents). the yamls in skyux-ia is also not doc'd i believe, but i'm guessing based on quick skimming them in the past that some subset of the `skyuxconfig.json` is what the yamls want, j/ in yaml form.

[slack thread](https://blackbaud.slack.com/archives/C013LANBY10/p1596726104308500) that prompted this.

also, i didnt investigate enough to determine if `searchUrl` was the _only_ thing missing.

**Comment by Blackbaud-SteveBrush** [comment]
Closing. We want to keep this as an "undocumented feature" since it's primarily used internal-only.

**Comment by Blackbaud-ColbyWhite** [comment]
@Blackbaud-SteveBrush , this does not address the ticket. I am internal and it's difficult for me to understand how to use this feature or even know that it's there. and the omnibar-docs seem to be behind auth. i dont have opinion on how to doc this, but the ticket is about the fact that it's not doc'd.

**Comment by blackbaud-johnly** [comment]
@Blackbaud-TerryHelems and I talked over this, and we came up with a plan to tweak the existing docs to better handle this. A lot of it is just linking to the IA repo's readme from appropriate places. I'm reopening this issue to make those changes.

**Comment by blackbaud-johnly** [comment]
Closing in favor of https://blackbaud.visualstudio.com/Products/_workitems/edit/1564681 so that we can track this in ADO instead of GitHub. I'll link from that bug to this closed issue for reference.
