### ISSUE TITLE
Update grid docs to specify unit for value of column's width property

### ISSUE THREAD

**Issue by blackbaud-johnly** [blackbaud/skyux2-docs#988]
Question came up on Slack about the property description in the docs that just says "Specifies the width of the column." and whether the value should be pixels, em, percentage, or any of those.

**Comment by jhenderson2099** [comment]
May want to indicate that this must be a _number_.  

That is, The grid column component cannot use something like "100%" which is not a number(from a JavaScript perspective. 
 In addition, you also can't use CSS `calc` as that allows for XSS attacks.  (You would need to bypass the security within the component and use the `DomSanitizer` to trust that.

**Comment by jhenderson2099** [comment]
One additional thing to document is what the behavior is within the component if this property is not specified or specified as `undefined`.

**Comment by blackbaud-johnly** [comment]
First part is addressed in https://github.com/blackbaud/skyux2-docs/pull/989. I didn't see the additional suggestions until after I merged that. I'll keep the issue open to address those points in another PR.

**Comment by blackbaud-johnly** [comment]
Addressed in https://github.com/blackbaud/skyux2-docs/pull/997.
